intern/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/urls.py
from django.urls import path
from . import views
# from .views import Logout

app_name="myapp"
urlpatterns = [
    path('', views.index, name='index'),
    path('signup', views.signup_view, name='signup_view'),
    path('login', views.login_view, name='login_view'),
    path('friends', views.friends, name='friends'),
    path('talk_room', views.talk_room, name='talk_room'),
    path('setting', views.setting, name='setting'),
    #追加です
    
    path("talk_room/<int:userlist_id>/", views.talk_room, name="talk_room"),
    # path("friends", views.get_return_link, name="get_return_link"),
    path('logout', views.logout_view, name="logout"),#ログアウトページへのパス
    path('change_email', views.change_email, name='change_email'),
    path('change_username/', views.change_username, name='change_username'),
    path('change_image/', views.change_image, name='change_image'),
    path('change_password/', views.change_password, name='change_password'),
    # path('changed/<int:changed_type>', views.changed, name='changed'),
    path('back_to_friends', views.back_to_friends, name='back_to_friends'),
    
    
]

myapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

#追記
from django.utils import timezone
import uuid

class CustomUser(AbstractUser):
    image = models.ImageField()#保存様式画像
    def __str__(self):
        return self.username
    
# class Room(models.Model):
#     id = models.UUIDField(primary_key=True, default=uuid.uuid4)
#     name = models.CharField(max_length=50)
#     created_at = models.DateTimeField(default=timezone.now)

    
class Message(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    # room = models.ForeignKey(
    #     # Room,
    #     blank=True,
    #     null=True,
    #     related_name='room_meesages',
    #     on_delete=models.CASCADE
    # )
    # name = models.CharField(max_length=50)
    
    sender = models.ForeignKey(CustomUser,on_delete=models.CASCADE,related_name="sender")
    recipient=models.ForeignKey(CustomUser,on_delete=models.CASCADE,related_name="recipient")
    content = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)
    # sender = models.IntegerField(null=False, blank=True)
    # recipient = models.IntegerField(null=False, blank=True)

myapp/forms.py
from django import forms
from .models import CustomUser
#ここ追記
from .models import Message
from django.contrib.auth import get_user_model
#ここまで追記

from django.contrib.auth.forms import UserCreationForm,AuthenticationForm,PasswordChangeForm
from django.contrib.auth.models import User

User=get_user_model()


class CustomPasswordChangeForm(PasswordChangeForm):
    class Meta:
        model = User
        fields = ['old_password', 'new_password1', 'new_password2']



class ChangeEmailForm(forms.ModelForm):
    new_email = forms.EmailField(label='新しいメールアドレス', required=True)

    class Meta:
        model = User
        fields = ['new_email']



class ChangeUsernameForm(forms.ModelForm):
    new_username = forms.CharField(label='新しいユーザー名', max_length=150)

    class Meta:
        model = User
        fields = ['new_username']

    def clean_new_username(self):
        username = self.cleaned_data['new_username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("このユーザー名は既に使用されています。")
        return username
    
class ChangeProfileImageForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['image']


class SignupForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields= ("username", "email", "image", "password1","password2")

class LoginForm(AuthenticationForm):
    pass


#ここから追記

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ("content",)

myapp/views.py
from django.shortcuts import redirect, render
from .forms import (
    SignupForm,
    LoginForm,
    MessageForm,
    ChangeEmailForm,
    ChangeUsernameForm,
    ChangeProfileImageForm,
    CustomPasswordChangeForm
)
from django.contrib.auth import login, logout,update_session_auth_hash
from .models import CustomUser
from .models import Message
from django.db.models import Q 
from operator import itemgetter

from django.contrib.auth.views import LogoutView
from django.contrib.auth.decorators import login_required

from django.contrib import messages



#戻るボタンできないかな
from urllib import parse
from django import template
from django.shortcuts import resolve_url


register = template.Library()

@login_required
def change_password(request):
    if request.method == 'POST':
        form = CustomPasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # ログイン維持
            # messages.success(request, 'パスワードが変更されました。')
            changed_type="パスワードが変更されました。"
            params={
                "changed_type":changed_type
            }
            return render(request, 'myapp/changed.html',params)
            # return redirect('/change_password')  
    else:
        form = CustomPasswordChangeForm(user=request.user)

    return render(request, 'myapp/change_password.html', {'form': form})

@login_required
def change_image(request):
    if request.method == 'POST':
        form = ChangeProfileImageForm(request.POST, request.FILES)
        if form.is_valid():
            user = request.user
            user.image = form.cleaned_data['image']
            user.save()
            # messages.success(request, 'アイコン画像が変更されました。')
            changed_type="アイコン画像が変更されました。"
            params={
                "changed_type":changed_type
            }
            return render(request, 'myapp/changed.html',params)
            # return redirect('/change_image')  
    else:
        form = ChangeProfileImageForm()

    return render(request, 'myapp/change_image.html', {'form': form})

@login_required
def change_email(request):
    if request.method == 'POST':
        form = ChangeEmailForm(request.POST)
        if form.is_valid():
            new_email = form.cleaned_data['new_email']
            request.user.email = new_email
            request.user.save()
            # messages.success(request, 'メールアドレスが変更されました。')
            changed_type="メールアドレスが変更されました。"
            params={
                "changed_type":changed_type
            }
            return render(request, 'myapp/changed.html',params)
            # return redirect('/change_email') 
    else:
        form = ChangeEmailForm()

    return render(request, 'myapp/change_email.html', {'form': form})


@login_required
def change_username(request):
    if request.method == 'POST':
        form = ChangeUsernameForm(request.POST)
        if form.is_valid():
            new_username = form.cleaned_data['new_username']
            request.user.username = new_username
            request.user.save()
            # messages.success(request, 'ユーザー名が変更されました。')
            changed_type="ユーザー名が変更されました。"
            params={
                "changed_type":changed_type
            }
            return render(request, 'myapp/changed.html',params)
            # return redirect('/change_username')  
    else:
        form = ChangeUsernameForm()

    return render(request, 'myapp/change_username.html', {'form': form})

def changed(request,params):
    return render(request, 'change_username.html', params)



@register.simple_tag
def get_return_link(request):
    friends_page = resolve_url('myapp:friends')  # 最新の日記一覧
    referer = request.environ.get('HTTP_REFERER')  # これが、前ページのURL

    # URL直接入力やお気に入りアクセスのときはリファラがないので、トップぺージに戻す
    if referer:

        # リファラがある場合、前回ページが自分のサイト内であれば、そこに戻す。
        parse_result = parse.urlparse(referer)
        if request.get_host() == parse_result.netloc:
            return referer

    return friends_page
# ここまで戻るボタンチャレンジ

# class Logout(LogoutView):
#     # template_name = 'index.html'
#     print("logout")

def logout_view(request):
    logout(request)
    messages="ログアウトしました"
    param={
        "messages":messages
    }

    return render(request, 'myapp/index.html',param)

def index(request):
    return render(request, "myapp/index.html")

def signup_view(request):
    # form= SignupForm()
    # return render(request, "myapp/signup.html", {'form':form})
    if request.method == 'POST':
        print(1)
        print(request.POST)

        form = SignupForm(request.POST, request.FILES)
        print(form.errors)
        if form.is_valid():
            # print(2)
            form.save()
            return render(request, 'myapp/index.html')

    else:
        form = SignupForm()
    
    param = {
        'form': form
    }

    return render(request, 'myapp/signup.html', param)






def login_view(request):
    if request.method == 'POST':
        form =LoginForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()

            if user:
                login(request, user)
                return redirect('/friends')
                # return render(request, 'myapp/friends.html')
                
    else:
        form = LoginForm()
    param = {
        'form': form,
    }
    
    return render(request, "myapp/login.html",param)

def friends(request):
    # print(1)
    users=CustomUser.objects.all()
    
    # print(users)
    # for user in users:
        # print(2)
        # print(user.username)
    login_user=request.user
    friends=CustomUser.objects.exclude(id=login_user.id)

    # messages=Message.objects.filter(sender=CustomUser.objects.get(id=userlist_id),recipient=request.user)
    message_list=[]
    no_message=[]
    got_message=[]
    for friend in friends:
        latest_message=Message.objects.filter(
            Q(
                sender=request.user,
                recipient=friend
            )|
            Q(
                sender=friend,
                recipient=request.user
            )
        ).order_by("created_at").last()
        if latest_message:
            got_message.append([friend, latest_message.content, latest_message.created_at])
        else:
            no_message.append([friend, None, None])

        #friends画面が時間順になるように
    got_message= sorted(got_message, key=itemgetter(2), reverse=True)
    message_list.extend(got_message)
    message_list.extend(no_message)
    
    params={
        "message_list":message_list       
    }

    return render(request, "myapp/friends.html",params)


    

def talk_room(request, userlist_id):
    # print(userlist_id)#int型


    users=CustomUser.objects.all()
    login_username=request.user
    userlist=[]
    for item in users:
        if not str(login_username)==item.username:
            userlist.append(item)
    


    if request.method == 'POST':
        
        print(request.POST)
        print(1)

        form = MessageForm(request.POST)
        message = form.save(commit=False)
        message.sender = request.user
        message.recipient =  CustomUser.objects.get(id=userlist_id)
        # print(3)
        message.save()
        form = MessageForm()#空にする


    else:
        form = MessageForm()

    messages=Message.objects.filter(
        Q(
            sender=request.user,
            recipient=CustomUser.objects.get(id=userlist_id)
        )|
        Q(
            sender=CustomUser.objects.get(id=userlist_id),recipient=request.user
        )
    ).order_by("created_at")
    # print(request.user)
    # print(CustomUser.objects.get(id=userlist_id))
    # print(messages)
    # print(users)
    # print(userlist_id)
    # print(Message.objects.get(sender=request.user))
    talking_username=CustomUser.objects.get(id=userlist_id)

    params={
        "data":users,
        "login_username":login_username,
        "userlist":userlist,
        "userlist_id":userlist_id,
        'form': form,
        'messages':messages,
        "talking_username":talking_username
    }
    

    # return render(request, 'myapp/signup.html', param)

    return render(request, "myapp/talk_room.html",params)

def back_to_friends(request):
    return redirect('/friends')



def setting(request):
    return render(request, "myapp/setting.html")

myapp/templates/myapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'myapp/css/base.css' %}" />
    {% block extra_style %}{% endblock %}
    <title>DeMiAインターン</title>
</head>
<body>
    {% block header %}
    <header class="header">
        <div class="header-container">
            <span class="header-container__title">
                {% block header-title %}{% endblock %}
            </span>
        </div>
    </header>
    {% endblock %}

    {% block content %}
    {% endblock %}

    {% block footer %}
    <footer class="footer">
        <div class="footer-container">
            <div class="footer-container__item">
                <a href="{% url 'myapp:friends' %}" class="footer-item__link">
                    <span class="footer-item__icon"><img src="{% static 'myapp/img/people-24px.svg' %}"></span>
                    <span class="footer-item__text">友達</span>
                </a>
            </div>
            <div class="footer-container__item">
                <a href="{% url 'myapp:setting' %}" class="footer-item__link">
                    <span class="footer-item__icon"><img src="{% static 'myapp/img/settings-black-18dp.svg' %}"></span>
                    <span class="footer-item__text">設定</span>
                </a>
            </div>
        </div>
    </footer>
    {% endblock %}
</body>
</html>

myapp/templates/myapp/change_email.html
{% extends 'myapp/base.html' %}

{% load static %}
{% block content %}
    <h2>メールアドレスの変更</h2>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">変更する</button>
    </form>
    {% if messages %}
        {% for message in messages %}
        <div class="alert">{{ message }}</div>
        {% endfor %}
    {% endif %}
{% endblock %}

myapp/templates/myapp/change_image.html
{% extends 'myapp/base.html' %}

{% load static %}

{% block content %}
    <h2>アイコンの変更</h2>
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">変更する</button>
    </form>
    {% if messages %}
        {% for message in messages %}
        <div class="alert">{{ message }}</div>
        {% endfor %}
    {% endif %}
{% endblock %}

myapp/templates/myapp/change_password.html
{% extends 'myapp/base.html' %}

{% load static %}

{% block content %}
    <h2>パスワードの変更（忘れないでね）</h2>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">変更する</button>
    </form>
    {% if messages %}
        {% for message in messages %}
        <div class="alert">{{ message }}</div>
        {% endfor %}
    {% endif %}
{% endblock %}

myapp/templates/myapp/change_username.html
{% extends 'myapp/base.html' %}

{% load static %}

{% block content %}
    <h2>ユーザー名の変更</h2>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">変更する</button>
    </form>
    {% if messages %}
        {% for message in messages %}
        <div class="alert">{{ message }}</div>
        {% endfor %}
    {% endif %}
{% endblock %}

myapp/templates/myapp/changed.html
{% extends 'myapp/base.html' %}

{% load static %}
{% block content %}
{%if changed_type%}
    
<h2>{{changed_type}}</h2>

{%endif%}
{% endblock %}

myapp/templates/myapp/friends.html
{% extends 'myapp/base.html' %}

{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>friends</title>
    <link rel="stylesheet" type="text/css" href="{% static 'myapp/css/friends.css' %}" />
    {% block extra_style %}<link rel="stylesheet" type="text/css" href="{% static 'myapp/css/friends.css' %}" />{% endblock %}
</head>
<body>
    {% block header %}
    <header class="header">
        <a href="{% url 'myapp:setting' %}" class="footer-item__link">
        <div class="header-container">
            
                <span class="user_icon">
                    <img src="{{ user.image.url }}"   class="userimage"/>
                </span>
            
            
            <span class="header-container__title">
                
                {% block header-title %}{{user}}の友達{% endblock %}
            </span>
        </div>
        </a>
    </header>
    {% endblock %}
    

    {% block content %}
    {% for userlist, content, created_at in message_list %}
        {% if userlist.image %}

        <a href="{% url 'myapp:talk_room' userlist.id %}"  class="user_link">
        
            <div class="user_tag">
                <div>
                    <img src="{{ userlist.image.url }}"   class="userimage"/>
                </div>
                <div class="username">{{userlist.username|truncatechars:11}}</div>

                {% if content %}
                <div class="content">{{ content|truncatechars:7 }}</div>
                
                {% else %}
                <div class="content">まだ話したことないユーザーです。話してみましょう！</div>
                {% endif %}      
                {% if content %}
                <div class="created_at">{{created_at}}</div> 
                {% endif %}     
                    {% comment %} {% if get_message.sender|stringformat:"s"　== userlist.username|stringformat:"s" %} {% endcomment %}
                        {% comment %} classから引っ張ってきた情報同士を比較するときは|stringformat:"s"で文字列にしないといけないようですね、class固有のtypeがあるようだ {% endcomment %}
            </div> 
                
        </a>       
        
                
        {% endif %} 
                
        


                        
    {% endfor %}

    <div>              
    ログイン中のユーザー:{{user}}
    </div>

    {% endblock %}
    
    

    
</body>
</html>

myapp/templates/myapp/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>index</title>
    <link rel="stylesheet" type="text/css" href="{% static 'myapp/css/index.css' %}" />   
</head>
<body>
    {%if messages%}
    
    <h2>{{messages}}</h2>

    {%endif%}
    
    
    <div class="log_in_div">
        <a href="{% url 'myapp:login_view' %}">

            <button class="log_in_button">
                <div class="long_in_botton_log_in">ログイン</div>
            </button>
        </a>
    </div>
    <div class="member_registration_div">
        <a href="{% url 'myapp:signup_view' %}">
            <button class="member_registration_button">
                <div class="member_registration_button_member_registration">会員登録</div>
            </button>
        </a>
    </div>

    
</body>
</html>

myapp/templates/myapp/login.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>login</title>
    <link rel="stylesheet" type="text/css" href="{% static 'myapp/css/login.css' %}" />
</head>
<body>
    <header class="login_first">ログイン</header><hr>
    
    <form action="{% url 'myapp:login_view' %}" method="post">
    {% csrf_token %}
        {{ form.as_p }}
        <p><input type="submit" value="ログイン"></p>
    </form>
    
</body>
</html>

myapp/templates/myapp/setting.html
{% extends 'myapp/base.html' %}

{% load static %}
{% block extra_style %}<link rel="stylesheet" type="text/css" href="{% static 'myapp/css/setting.css' %}" />{% endblock %}
{% block header-title %}設定{% endblock %}


{% block content %}


    <div class="setting_option">
        <a href="{% url 'myapp:change_username' %}">

            <button class="setting_option_button">
                <div class="setting_option_content">ユーザー名変更</div>
            </button>
        </a>
    </div>
    <div class="setting_option">
        <a href="{% url 'myapp:change_email' %}">

            <button class="setting_option_button">
                <div class="setting_option_content">メールアドレス変更</div>
            </button>
        </a>
    </div>
    <div class="setting_option">
        <a href="{% url 'myapp:change_image' %}">

            <button class="setting_option_button">
                <div class="setting_option_content">アイコン変更</div>
            </button>
        </a>
    </div>
    <div class="setting_option">
        <a href="{% url 'myapp:change_password' %}">

            <button class="setting_option_button">
                <div class="setting_option_content">パスワード変更</div>
            </button>
        </a>
    </div>
    <div class="setting_option">
        <a href="{% url 'myapp:logout' %}">

            <button class="setting_option_button">
                <div class="setting_option_content">ログアウト</div>
            </button>
        </a>
    </div>
{% endblock %}

myapp/templates/myapp/signup.html
{% extends 'myapp/base.html' %}
{% load static %}
<!-- <!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>signup</title>
    <link rel="stylesheet" type="text/css" href="{% static 'myapp/css/signup.css' %}" />
    
</head>
<body> -->
    <!-- <header class="member_registration_first">会員登録</header><hr> -->

    {% block header-title %}会員登録{% endblock %}
    {% block extra_style %}<link rel="stylesheet" type="text/css" href="{% static 'myapp/css/signup.css' %}" />{% endblock %}
    <!-- <div class="member_registration_second">
        <form action="{% url 'signup_view' %}"  method="post">
            <fieldset class="form-block">
                <div><legend class="form-title">Usename:</legend></div>
                <div class="form-input"><input type="text"  name="person"   class="input-text"  required></div>
            </fieldset>

            <fieldset class="form-block">
                <div><legend class="form-title">Email<br>address:</legend></div>
                <div   class="form-input"><input type="email"     class="input-text" required></div>
            </fieldset>

            <fieldset class="form-block">
                <div><legend class="form-title">Password:</legend></div>
                <div   class="form-input"><input type="password"  class="input-text" required></div>
            </fieldset>

            <fieldset class="form-block">
                <div><legend class="form-title">Password<br>confirmation:</legend></div>
                <div   class="form-input"><input type="password"  class="input-text" required></div>
            </fieldset>

            <fieldset class="form-block">
                <div><legend class="form-title">Img:</legend></div>
                <div   class="file"><input type="file"  class="input-text" required></div>
            </fieldset>

            <div class="submit-btn">
                <input type="submit" value="subimit" > 
                    
                
            </div>
        </form>

    
    </div> -->
    {% block content %}
    
    <form method="post" enctype="multipart/form-data">
        <form action="{% url 'myapp:signup_view' %}" method="post">
            {% csrf_token %}
            <div class="question"><div class="question_name">username:</div>
            {{form.username}}</div>
            <br>
            <div class="question"><div class="question_name">Email<br>address:</div>{{form.email}}</div>
            
            
            <br>
            <div class="question"><p class="question_name">Password:</p>
            <p>{{form.password1}}</p></div>
            <br>
            <div class="question"><div class="question_name">Password<br>confirmation:</div>
            {{form.password2}}</div>
            <br>
            <div class="question"><div class="question_name">Img:</div>
            {{form.image}}</div>
            <input type="submit" value="Submit">
        </form>
    </form>
    {% endblock %}
    {% block footer %}
    {% endblock %}
    
<!-- </body>
</html> -->

myapp/templates/myapp/talk_room.html
{% extends 'myapp/base.html' %}

{% load static %}

{% block header-title %}<a href="{% url 'myapp:back_to_friends'  %}">＜戻る</a>
{% comment %} <a href="{% get_return_link request %}">戻る</a> {% endcomment %}
あなたと{{talking_username}}のトークルーム{% endblock %}

{% block extra_style %}<link rel="stylesheet" type="text/css" href="{% static 'myapp/css/talk_room.css' %}" />{% endblock %}
{% block content %}
{% for message in messages %}
{% comment %} userは勝手に送られるらしいよ {% endcomment %}
    {% if message.sender == user %}
    <div class="i_sent"><div class="kaigyou">{{ message.content}}</div>{{message.sender}}&nbsp;to&nbsp; {{message.recipient}}<div class="date">{{message.created_at}}</div></div>
    {% else %}
    <div class="you_sent"><div class="kaigyou">{{ message.content}}</div> {{message.sender}}&nbsp;to&nbsp; {{message.recipient}}<div class="date">{{message.created_at}}</div></div>
    {% endif %} 
{% endfor %}
{% endblock %}


{% block footer %}
<footer>
    <form method="post" enctype="multipart/form-data">
        <form  action="{% url 'myapp:talk_room' %}" class="messagebox" method="post">
            {% csrf_token %}
            <div>{{ form.content }}</div>
            <button class="messagebow_btn" type="submit">送信</button>
        </form>
    </form>
</footer>

{% comment %} <footer class="footer">
    <div class="footer-container">
        <div class="footer-container__item">
            <form method="post" enctype="multipart/form-data">
                <form  action="{% url 'myapp:talk_room' %}" class="messagebox" method="post">
                    {% csrf_token %}
                    
                        {{ form.content }}<button class="messagebox_btn" type="submit">送信</button>
                      
                        
                    
                </form>
            </form>
        </div>
        
    </div>
</footer> {% endcomment %}


{% endblock %}